import { StyleSheet } from 'react-native';

export const registerStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  centeredContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 12,
  },
  formContainer: {
    width: "92%",
    maxWidth: 420,
    backgroundColor: "rgba(255,255,255,0.96)",
    padding: 28,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 12,
    marginVertical: 20,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 30,
    paddingHorizontal: 14,
  },
  logo: {
    width: 225,
    height:225,
    alignSelf: "center",
    marginBottom: -70,

  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#198754',
    marginBottom: 20,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#198754",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    fontSize: 15,
    backgroundColor: "#f8fffe",
    minHeight: 48,
    color: "#000",
  },
  registerButton: {
    width: "100%",
    backgroundColor: "#28a463",
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 24,
    alignItems: "center",
    marginTop: 12,
    marginBottom: 10,
    minHeight: 50,
    shadowColor: '#1b5e20',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 6,
  },
  registerButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  loginText: {
    marginTop: 10,
    marginBottom: 5,
    color: '#198754',
    textAlign: 'center',
    textDecorationLine: 'underline',
    fontSize: 13,
  },
  errorText: {
    color: "#d32f2f",
    marginBottom: 15,
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 14,
  },

  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
  },
  loadingContent: {
    alignItems: 'center',
  },
  loadingLogo: {
    width: 200,
    height: 200,
    marginBottom: 30,
  },
  loadingSpinner: {
    marginVertical: 20,
  },
  loadingText: {
    fontSize: 18,
    color: '#6c757d',
    fontWeight: '500',
  },
});