import { StyleSheet } from 'react-native';

export const registerStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  centeredContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  formContainer: {
    width: "80%",
    maxWidth: 380,
    backgroundColor: "rgba(255,255,255,0.95)",
    padding: 25,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    marginVertical: 20,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 10,
  },
  logo: {
    width: 200,
    height: 200,
    marginBottom: -40,
    alignSelf: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#198754',
    marginBottom: 20,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#198754",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    fontSize: 15,
    backgroundColor: "#f8fffe",
    minHeight: 45,
    color: "#000",
  },
  registerButton: {
    width: "100%",
    backgroundColor: "#198754",
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 8,
    minHeight: 48,
  },
  registerButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  loginText: {
    marginTop: 10,
    marginBottom: 5,
    color: '#198754',
    textAlign: 'center',
    textDecorationLine: 'underline',
    fontSize: 13,
  },
  errorText: {
    color: "#d32f2f",
    marginBottom: 15,
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 14,
  },

  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
  },
  loadingContent: {
    alignItems: 'center',
  },
  loadingLogo: {
    width: 200,
    height: 200,
    marginBottom: 30,
  },
  loadingSpinner: {
    marginVertical: 20,
  },
  loadingText: {
    fontSize: 18,
    color: '#6c757d',
    fontWeight: '500',
  },
});